### ISSUE TITLE
Add my analyzer for improving switching on closed type hierarchies

### ISSUE THREAD

**Issue by shuebner** [Cybermaxs/awesome-analyzers#27]
Hi,
I hope this repo is still active.
I created an analyzer that suppresses exhaustiveness warnings when `switch`ing on an instance of a closed type hierarchy and  matching all types in the hierarchy. It is NRT-aware and supports a couple of patterns:

https://github.com/shuebner/ClosedTypeHierarchyDiagnosticSuppressor

I would like to add it to the list.
If you would like me to create PR directly, please tell me.

**Comment by Bosch-Eli-Black** [comment]
If you create a PR, I think the repo owner will probably merge it 🙂  He merges most PR's that are sent to him, I think 🙂

**Comment by shuebner** [comment]
created PR #28
